export * from "@MELocalization/fee/feeTranslationEn";
export * from "@MELocalization/signIn/signInTranslationEn";
export * from "@MELocalization/sidebar/sidebarTranslationEn";
export * from "@MELocalization/profile/profileTranslationEn";
export * from "@MELocalization/facility/facilityTranslationEn";
export * from "@MELocalization/dashboard/dashboardTranslationEn";
export * from "@MELocalization/admission/admissionTranslationEn";
export * from "@MELocalization/academicClass/academicClassTranslationEn";
export * from "@MELocalization/admissionDocument/admissionDocumentTranslationEn";
