/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  safelist: [
    // Primary color classes
    'bg-primary',
    'text-primary',
    'border-primary',
    'text-primary-foreground',
    'bg-primary/10',
    'text-primary/80',
    // Secondary color classes
    'bg-secondary',
    'text-secondary',
    'border-secondary',
    'text-secondary-foreground',
    'bg-secondary/10',
    'text-secondary/80',
    // Custom color backgrounds
    'bg-danger',
    'bg-warning', 
    'bg-success',
    'bg-info',
    'bg-neutral',
    'bg-dark',
    // Custom color text
    'text-danger',
    'text-warning',
    'text-success',
    'text-info',
    'text-neutral',
    'text-dark',
    // Custom color borders
    'border-danger',
    'border-warning',
    'border-success',
    'border-info',
    'border-neutral',
    'border-dark',
    // Custom color foregrounds
    'text-danger-foreground',
    'text-warning-foreground',
    'text-success-foreground',
    'text-info-foreground',
    'text-neutral-foreground',
    'text-dark-foreground',
    // Custom color backgrounds with opacity
    'bg-danger/10',
    'bg-warning/10',
    'bg-success/10',
    'bg-info/10',
    'bg-neutral/10',
    'bg-dark/10',
    // Custom color text with opacity
    'text-danger/80',
    'text-warning/80',
    'text-success/80',
    'text-info/80',
    'text-neutral/80',
    'text-dark/80'
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#040D12",
          foreground: "#ffffff",
          50: "#f8f9fa",
          100: "#e9ecef", 
          200: "#dee2e6",
          300: "#ced4da",
          400: "#6c757d",
          500: "#495057",
          600: "#343a40",
          700: "#212529",
          800: "#0a0e12",
          900: "#040D12",
        },
        secondary: {
          DEFAULT: "#FAF0E6",
          foreground: "#0f172a",
          50: "#fdfcfb",
          100: "#faf7f3", 
          200: "#f5f0e8",
          300: "#f0e7dc",
          400: "#e8dccb",
          500: "#FAF0E6",
          600: "#d4c2a8",
          700: "#b8a082",
          800: "#9c825f",
          900: "#7a6548",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        danger: {
          DEFAULT: "#ab4459",
          foreground: "#ffffff",
          50: "#fdf2f4",
          100: "#fce7ea", 
          200: "#f9d0d7",
          300: "#f5a8b7",
          400: "#ee7591",
          500: "#e2426d",
          600: "#d02356",
          700: "#ab4459",
          800: "#8f3c4a",
          900: "#7a3844",
        },
        success: {
          DEFAULT: "#60b159",
          foreground: "#ffffff",
          50: "#f0f9f0",
          100: "#dcf2da", 
          200: "#bce5b8",
          300: "#91d48b",
          400: "#6bc062",
          500: "#60b159",
          600: "#4a9142",
          700: "#3d7537",
          800: "#345d30",
          900: "#2d4e2a",
        },
        warning: {
          DEFAULT: "#d17615",
          foreground: "#ffffff",
          50: "#fdf7ed",
          100: "#fbedd4", 
          200: "#f6d7a8",
          300: "#efbc71",
          400: "#e89838",
          500: "#d17615",
          600: "#b85d0f",
          700: "#98470f",
          800: "#7c3914",
          900: "#663014",
        },
        dark: {
          DEFAULT: "#1b1b1d",
          foreground: "#ffffff",
          50: "#f8f8f8",
          100: "#f0f0f0", 
          200: "#e4e4e4",
          300: "#d1d1d1",
          400: "#b4b4b4",
          500: "#9a9a9a",
          600: "#818181",
          700: "#6a6a6a",
          800: "#5a5a5a",
          900: "#1b1b1d",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        danger: {
          DEFAULT: "hsl(var(--danger))",
          foreground: "hsl(var(--danger-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        neutral: {
          DEFAULT: "hsl(var(--neutral))",
          foreground: "hsl(var(--neutral-foreground))",
        },
        dark: {
          DEFAULT: "hsl(var(--dark))",
          foreground: "hsl(var(--dark-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-up": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "collapsible-down": {
          from: { height: "0" },
          to: { height: "var(--radix-collapsible-content-height)" },
        },
        "collapsible-up": {
          from: { height: "var(--radix-collapsible-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.2s ease-out",
        "slide-up": "slide-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}
