import { ADMISSION_APPLICATION_STATUS } from "@MEHelpers/enums/admissionEnum";

// ---------------------------------------------------------------------------
// Static constants (no re-creation on every render)
// ---------------------------------------------------------------------------

const ALLOWED_TRANSITIONS = {
  [ADMISSION_APPLICATION_STATUS.SUBMITTED]: [
    ADMISSION_APPLICATION_STATUS.UNDER_REVIEW,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.UNDER_REVIEW]: [
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFICATION_PENDING,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFICATION_PENDING]: [
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFIED,
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_UNVERIFIED,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.DOCUMENTS_UNVERIFIED]: [
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFIED,
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_UNVERIFIED,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFIED]: [
    ADMISSION_APPLICATION_STATUS.APPROVED,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.REJECTED]: [
    ADMISSION_APPLICATION_STATUS.APPROVED,
  ],
  [ADMISSION_APPLICATION_STATUS.FEES_PENDING]: [
    ADMISSION_APPLICATION_STATUS.FEES_PAID,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.FEES_PAID]: [
    ADMISSION_APPLICATION_STATUS.SELECTED,
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
  [ADMISSION_APPLICATION_STATUS.SELECTED]: [
    ADMISSION_APPLICATION_STATUS.REJECTED,
  ],
};

/**
 * Status transitions that require an appointment date field.
 * Key: currentStatus | Value: set of next statuses that need a date picker.
 */
const APPOINTMENT_DATE_REQUIRED = {
  [ADMISSION_APPLICATION_STATUS.UNDER_REVIEW]: new Set([
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFICATION_PENDING,
  ]),
  [ADMISSION_APPLICATION_STATUS.APPROVED]: new Set([
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFICATION_PENDING,
    ADMISSION_APPLICATION_STATUS.FEES_PENDING,
  ]),
  [ADMISSION_APPLICATION_STATUS.DOCUMENTS_VERIFICATION_PENDING]: new Set([
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_UNVERIFIED,
  ]),
  [ADMISSION_APPLICATION_STATUS.DOCUMENTS_UNVERIFIED]: new Set([
    ADMISSION_APPLICATION_STATUS.DOCUMENTS_UNVERIFIED,
  ]),
};

export { ALLOWED_TRANSITIONS, APPOINTMENT_DATE_REQUIRED };